create extension if not exists pgcrypto;
create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, name text not null default '', course text not null default '', created_at timestamptz not null default now());
create table if not exists public.activities (id uuid primary key default gen_random_uuid(), creator_id uuid not null references public.profiles(id) on delete cascade, name text not null, type text not null, time text not null, place text not null, spots integer not null check (spots >= 2 and spots <= 100), created_at timestamptz not null default now());
create table if not exists public.participants (activity_id uuid not null references public.activities(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade, created_at timestamptz not null default now(), primary key(activity_id,user_id));
create index if not exists participants_user_id_idx on public.participants(user_id);
create index if not exists activities_creator_id_idx on public.activities(creator_id);
alter table public.profiles enable row level security;
alter table public.activities enable row level security;
alter table public.participants enable row level security;
drop policy if exists profiles_select on public.profiles;
drop policy if exists profiles_insert on public.profiles;
drop policy if exists profiles_update on public.profiles;
drop policy if exists activities_select on public.activities;
drop policy if exists activities_insert on public.activities;
drop policy if exists activities_update on public.activities;
drop policy if exists activities_delete on public.activities;
drop policy if exists participants_select on public.participants;
drop policy if exists participants_insert on public.participants;
drop policy if exists participants_delete on public.participants;
create policy profiles_select on public.profiles for select to authenticated using (true);
create policy profiles_insert on public.profiles for insert to authenticated with check ((select auth.uid()) = id);
create policy profiles_update on public.profiles for update to authenticated using ((select auth.uid()) = id) with check ((select auth.uid()) = id);
create policy activities_select on public.activities for select to authenticated using (true);
create policy activities_insert on public.activities for insert to authenticated with check ((select auth.uid()) = creator_id);
create policy activities_update on public.activities for update to authenticated using ((select auth.uid()) = creator_id) with check ((select auth.uid()) = creator_id);
create policy activities_delete on public.activities for delete to authenticated using ((select auth.uid()) = creator_id);
create policy participants_select on public.participants for select to authenticated using (true);
create policy participants_insert on public.participants for insert to authenticated with check ((select auth.uid()) = user_id and exists (select 1 from public.activities a where a.id=activity_id and (select count(*) from public.participants p where p.activity_id=a.id) < a.spots));
create policy participants_delete on public.participants for delete to authenticated using ((select auth.uid()) = user_id);
grant select,insert,update on public.profiles to authenticated;
grant select,insert,update,delete on public.activities to authenticated;
grant select,insert,delete on public.participants to authenticated;
